
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
export const firebaseConfig = {
  "projectId": "studio-4619411114-e9a34",
  "appId": "1:949195446748:web:84ec3305a50112cbeb9719",
  "storageBucket": "studio-4619411114-e9a34.appspot.com",
  "apiKey": "AIzaSyBVf0j_mCdt-wF7Pq7YGs9a8_sGfInGVJQ",
  "authDomain": "studio-4619411114-e9a3d.firebaseapp.com",
  "messagingSenderId": "949195446748"
};
